task: portfolio
model: gen-dfl
generator: cnf
seeds: [42, 43, 44]
n: 200
m: 50
deg: 5
noise_width: 20
beta: 100
alpha: 1.0
num_generated_samples: 200
num_epochs: 10
p_theta_pretrain_epochs: 50
contextual_pretrain_epochs: 30

